#!/bin/sh
set -e

case "$1" in
    purge)
        if command -v systemctl >/dev/null 2>&1; then
            deb-systemd-helper purge scrolllock-led-daemon.service || true
            deb-systemd-helper mask scrolllock-led-daemon.service >/dev/null || true
        fi
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
esac

#DEBHELPER#
