#!/bin/sh
set -e

case "$1" in
    configure)
        if command -v systemctl >/dev/null 2>&1; then
            deb-systemd-helper unmask scrolllock-led-daemon.service >/dev/null || true
            if deb-systemd-helper --quiet was-enabled scrolllock-led-daemon.service; then
                deb-systemd-helper enable scrolllock-led-daemon.service >/dev/null || true
            else
                deb-systemd-helper enable scrolllock-led-daemon.service >/dev/null || true
            fi
            systemctl daemon-reload >/dev/null || true
            systemctl start scrolllock-led-daemon.service >/dev/null || true
        fi
        ;;
esac
